config/routes.rb
Rails.application.routes.draw do
mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :posts do
    resources :comments
  end
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :subscribers
  resources :spaces do
    put :favorite, on: :member
    resources :reviews, except: [:index]
    resources :pictures
    resources :comments


    collection do
      get 'search'
    end
  end

  match "/404", :to => "errors#not_found", :via => :all

  root 'static#home'

  match "contact" => "contacts#create", :via => :post, :as => :create_contact
  get '/pending' => "static#pending"
  get '/users/:id' => 'static#user_profile'
  get '/spaces2' => "spaces#index2"
  get '/howitworks' => "static#howitworks"
  get '/contact' => "contacts#new"
  get '/blog' => "static#blog"
  get '/home1' => "static#home1"
  get '/map' => "spaces#map"
  get '/my_spaces' => "spaces#my_spaces"
  get '/my_reviews' => "reviews#my_reviews"
  get '/favorites' => "spaces#favorites"


end

app/models/space.rb
class Space < ActiveRecord::Base
  before_save do
    self.feature.gsub!(/[\[\]\"]/, "") if attribute_present?("feature")
  end

after_create :send_new_space_mail, :send_new_space_mail_notification
 def send_new_space_mail
   Notifier.new_space_email(self).deliver
 end

 def send_new_space_mail_notification
   Notifier.new_space_email_notification(self).deliver
 end

  has_many :reviews
  belongs_to :user
  has_many :favorite_spaces
  has_many :favorited_by, through: :favorite_spaces, source: :user
  belongs_to :category
  has_many :pictures
  validates_presence_of :name, :category, :description, :address1, :city, :country, :image, :phone, feature:[]
  geocoded_by :full_address
  after_validation :geocode

  has_attached_file :image, styles: { thumb: ["180x140#", :jpg],
                            small: ['350x225#', :jpg],
                            popular: ['265x225#'],
                            recent: ['365x225#']},
                  convert_options: { thumb: "-quality 75 -strip",
                                     small: "-quality 85 -strip" }


  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/


  def full_address
    [address1, address2, city, state, country, zipcode].join(', ')
  end


  def self.search(params)
    spaces = Space.where(category_id: params[:category].to_i)
    spaces = spaces.where("name like ? or description like ?", "%#{params[:search]}%", "%#{params[:search]}%") if params[:search].present?
    spaces = spaces.near(params[:location], 20) if params[:location].present?
    spaces
  end

  def self.search_map(params)
    spaces = Space.where(category_id: params[:category].to_i)
    spaces = spaces.where("name like ? or description like ?", "%#{params[:search]}%", "%#{params[:search]}%") if params[:search].present?
    spaces = spaces.near(params[:location], 20) if params[:location].present?
    spaces
  end


end

app/controllers/spaces_controller.rb
class SpacesController < ApplicationController
  before_action :authenticate_user!, only: [:create, :new, :index, :show, :my_spaces, :favorites]
  before_action :set_space, only: [:show, :edit, :update, :destroy]
  

  # GET /spaces
  # GET /spaces.json
  def index
    @spaces = Space.all.paginate(:page => params[:page], :per_page => 6)
    @reviews = Review.where(space_id: @space)
    if @reviews.blank?
      @avg_rating = 0
    else
      @avg_rating = @reviews.average(:rating).round(2)
    end

    @hash = Gmaps4rails.build_markers(@spaces) do |space, marker|
     marker.lat space.latitude
     marker.lng space.longitude
     marker.infowindow render_to_string(:partial => "/spaces/infowindow", :locals => { :object => space})
   end
  end


  def show
    @space = Space.find(params[:id])
    if @space.approved? == false
      redirect_to pending_path
    end
    @reviews = Review.where(space_id: @space)
    @picture = Picture.where(space_id: @space)

    if @reviews.blank?
      @avg_rating = 0
    else
      @avg_rating = @reviews.average(:rating).round(2)
    end

    @features = @space.feature.split(',')

    @hash = Gmaps4rails.build_markers(@space) do |space, marker|
     marker.lat space.latitude
     marker.lng space.longitude

    end
  end


  def new
    @space = Space.new
  end


  def map
    @spaces = Space.all
  end

  # GET /spaces/1/edit
  def edit
  end

  # POST /spaces
  # POST /spaces.json
  def create
    @space = Space.new(space_params)
    @space.user_id = current_user.id
    respond_to do |format|
      if @space.save
        format.html { redirect_to @space, notice: 'Space was successfully created.' }
        format.json { render :show, status: :created, location: @space }
      else
        format.html { render :new }
        format.json { render json: @space.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /spaces/1
  # PATCH/PUT /spaces/1.json
  def update
    respond_to do |format|
      if @space.update(space_params)
        format.html { redirect_to @space, notice: 'Space was successfully updated.' }
        format.json { render :show, status: :ok, location: @space }
      else
        format.html { render :edit }
        format.json { render json: @space.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spaces/1
  # DELETE /spaces/1.json
  def destroy
    @space.destroy
    respond_to do |format|
      format.html { redirect_to spaces_url, notice: 'Space was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    @spaces = Space.search(params).paginate(:page => params[:page], :per_page => 6)
    @hash = Gmaps4rails.build_markers(@spaces) do |space, marker|
      marker.lat space.latitude
      marker.lng space.longitude
      marker.json({:id => space.id })
      marker.infowindow render_to_string(:partial => "/spaces/infowindow", :locals => { :object => space})
    end
  end

  def my_spaces
    @spaces = Space.where(user_id: current_user.id).paginate(:page => params[:page], :per_page => 5)
  end

  def favorites
    @spaces = current_user.favorites.paginate(:page => params[:page], :per_page => 5)
  end

  def favorite
      type = params[:type]
      @space = Space.find(params[:id])
      if type == "favorite" && current_user
        current_user.favorites << @space
        redirect_to :back, notice: 'Added to your Favorites!'

      elsif type == "unfavorite"
        current_user.favorites.delete(@space)
        redirect_to :back, notice: 'Removed from your Favorites!'

      elsif !(current_user)
        redirect_to :new_user_registration, notice: "Create an account to save your favorite Spaces!"

      else
        # Type missing, nothing happens
        redirect_to :back, notice: 'Nothing happened.'
      end
    end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_space
      @space = Space.find(params[:id])
    end

    def approved
      if @space.approved? == false
        redirect_to pending_path
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def space_params
      params.require(:space).permit(:name, :category_id, :user_id, :description, :address1, :address2, :city, :state, :country, :zipcode, :phone, :website, :facebook_url, :twitter_url, :instagram_url, :image, feature:[])
    end
end

app/helpers/spaces_helper.rb
module SpacesHelper

  def checked(area)
    @space.feature.nil? ? false : @space.feature.match(area)
  end

end

app/views/spaces/_infowindow.html.erb
<%= link_to "#{object.name}", space_path(object) %>

app/views/spaces/_search_map.html.erb
<script src="//maps.google.com/maps/api/js?key=AIzaSyDrG6_o9uHuGiIPiOipNnsZj_Jbizir93w"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->


<div style='width: 800px;'>
 <div class="map" id="map" style='width: 800px; height: 400px;'></div>
</div>

<script type="text/javascript">
handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers(<%=raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});
</script>

app/views/spaces/edit.html.erb
<div id="page-content">
  <div class="container">
    <ol class="breadcrumb">
      <li><a href="/">Home</a></li>
      <li><a href="<%=space_path(@space)%>"><%=@space.name%></a></li>
      <li class="active">Edit</li>
    </ol>
    <!--end breadcrumb-->
    <section class="page-title center">
      <h1>Edit the Space</h1>
    </section>

<%= render 'form' %>

app/views/spaces/favorites.html.erb
<div id="page-content">
  <div class="container">
    <ol class="breadcrumb">
      <li><a href="/">Home</a></li>
      <li class="active">My Favorites</li>
    </ol>
    <!--end breadcrumb-->
    <section class="page-title">
      <h1>My Favorites</h1>
    </section>
    <!--end page-title-->
    <section>
      <div class="my-items table-responsive">
        <table class="table">
          <thead>
            <tr>
              <th>Favorites</th>
              <th>Remote Friendly</th>
              <th># of Favorites</th>
              <th>Reviews</th>
              <th>Rating</th>
              <th>Last Edited</th>
            </tr>
          </thead>
          <tbody>
            <% @spaces.each do |space| %>
            <tr class="my-item">
              <td>
                <div class="image-wrapper">
                  <%if space.reviews.average(:rating) != nil && space.reviews.average(:rating) > 4 %>
                  <div class="circle" data-toggle="tooltip" data-placement="right" title="Top Listing"><i class="fa fa-thumbs-up"></i></div>
                  <%end%>
                  <div class="image" style="overflow: hidden;">
                    <%= image_tag space.image.url(:thumb) %>
                  </div>
                </div>
                <div class="info">
                  <h2><%= link_to space.name, space_path(space) %></h2>
                  <figure class="location"><%=space.city%>, <%=space.state%></figure>
                  <figure class="label label-info"><%=space.category.name%></figure>
                  <div class="additional-info">
                    <!-- <span><i class="fa fa-coffee"></i></span> -->
                    <span class="price-info"> <span class="price"></span><span class="appendix"></span></span>
                  </div>
                  <!--end additional-info-->
                </div>
                <!--end info-->
              </td>
              <% if space.reviews.average(:rating) != nil && space.reviews.average(:rating) > 3.8 && space.feature["Wifi"] != nil%>
              <td><div class="featured yes"><i class="fa fa-check"></i><aside></aside></div></td>
              <%else%>
              <td></td>
              <% end %>
              <td class="views"><%=space.favorite_spaces.count%></td>
              <td class="reviews"><%=space.reviews.count(:rating)%></td>
              <td class="rating">
                <% if space.reviews.blank? %>
                <p>No Reviews Yet!</p>
                <%else%>
                <div class="rating-passive" data-rating=<%=space.reviews.average(:rating)%>>
                  <span class="stars"></span><br>
                  <span class="reviews"><%="Average Rating: "%><%=space.reviews.average(:rating)%></span>
                </div>
                <%end%>
                </div>
              </td>
              <td class="last-edited"><%=space.updated_at.strftime("%b %d, %Y") + " at " + space.updated_at.strftime("%H:%M")%>
                <span class="last-edit">Last edited: <%=space.updated_at.strftime("%H:%M")%></span>
                <div class="edit-options">
                  <a href="<%=edit_space_path(space)%>" class="link icon"><i class="fa fa-edit"></i>Edit</a>
                  <a href="<%=space_path(space)%>" class="link icon"><i class="fa fa-comment"></i>Reviews</a>
                </div>
                <!--end edit-options-->
              </td>
            </tr>
            <%end%>
          </tbody>
        </table>
      </div>
      <!--end my-items-->
    </section>
    <section>
      <div class="center">
<%= will_paginate @spaces %>
      </div>
    </section>
  </div>
  <!--end container-->
</div>

app/views/spaces/index.html.erb
<script src="//maps.google.com/maps/api/js?key=AIzaSyDrG6_o9uHuGiIPiOipNnsZj_Jbizir93w"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->


<div class="page-wrapper">
  <div id="page-content">
    <div class="container">
      <ol class="breadcrumb">
        <li><a href="/">Home</a></li>
        <li class="active">Spaces</li>
      </ol>

      <section class="page-title">
        <h1>Find Your Space</h1>
      </section>
      <!--end section-title-->



      <section>
        <div class="search-results-controls clearfix">
          <div class="pull-left">
            <a href="" class="circle-icon"><i class="social_delicious" style="display: none;"></i></a>
          </div>
          <!--end left-->
          <!-- <div class="pull-right">
          <div class="input-group inputs-underline min-width-150px">
          <select class="form-control selectpicker" name="sort">
          <option value="">Sort by</option>
          <option value="1">Price</option>
          <option value="2">Distance</option>
          <option value="3">Title</option>
        </select>
      </div>
    </div> -->
    <!--end right-->
  </div>
  <!--end search-results-controls-->
</section>
<section>

  <section>
    <div style='width: 100%;' id="show_map">
      <div class="map" id="map" style='width: 100%; height: 500px;'></div>
    </div>
  </section>


  <div class="row">
    <% @spaces.each do |space| %>
    <div class="col-md-4 col-sm-4">
      <div class="item" data-id="1">
        <span>
          <%=image_tag space.image.url(:small), class: "image" %>
          <div class="description">
            <div class="label label-default"><%= "#{space.category.name}"%></div>
            <h3 style="margin-top: 5px; margin-bottom: 5px;"><%= link_to "#{space.name}", space_path(space), style: "color: white; text-shadow: 0px 1px 1px rgba(0, 0, 0, 0.5);"  %></h3>
            <h4 style="margin: 0;"><%=space.city%>, <%=space.state.capitalize%></h4>
          </div>
          <!--end description-->



        </span>
        <!--end image-->
        <div class="additional-info">
          <div class="rating-passive" data-rating=<%=@spaces[-1].reviews.average(:rating)%>>
            <div id="star"></div>
            <% if space.reviews.average(:rating) == nil %>
            <span class="reviews"><%= link_to "Be the first to Review!", space%></span>
            <%else%>
            <span class="reviews"><%=space.reviews.average(:rating)%></span>
            <span class="star-rating" data-score=<%=@spaces[-1].reviews.average(:rating)%> ></span>
            <%end%>
            <% if current_user.favorites.include? space %>
            <div class="fav_button" style="float: right;">
              <%= link_to "Unfavorite", favorite_space_path(space, type: "unfavorite"), class: "btn btn-primary btn-rounded btn-xs", method: :put %>
            </div>
            <%elsif current_user%>
            <div class="fav_button" style="float: right;">
              <%= link_to "Favorite", favorite_space_path(space, type: "favorite"), class: "btn btn-primary btn-rounded btn-xs", method: :put %>
            </div>
            <% end %>
          </div>

          <!--end controls-more-->
        </div>
        <!--end additional-info-->
        <!--end item-->

      </div>
    </div>
    <%end%>
    <!--<end col-md-3-->
  </div>
  <!--end row-->
</div>
</section>
<section>
  <div class="center">
    <nav aria-label="Page navigation">
      <ul class="pagination">
        <%= will_paginate @spaces %>
      </ul>
    </nav>
  </div>
</section>


</div>

<a href="#page-header" class="to-top scroll" data-show-after-scroll="600"><i class="arrow_up"></i></a>

<script>
$('.star-rating').raty({
  path: '/assets',
  readOnly: true,
  score: function() {
    return $(this).attr('data-score');
  }
});
</script>

<script type="text/javascript">
handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers(<%=raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});
</script>

<script type="text/javascript">
$(function() {
  $('.circle-icon').click(function(event){
    event.preventDefault();
    $('#map').toggle();
  });
});
</script>

app/views/spaces/map.html.erb
<script src="//maps.google.com/maps/api/js?key=AIzaSyDrG6_o9uHuGiIPiOipNnsZj_Jbizir93w"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->


<div style='width: 800px;'>
 <div class="map" id="map" style='width: 800px; height: 400px;'></div>
</div>


<script type="text/javascript">
handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers(<%=raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});
</script>

app/views/spaces/my_spaces.html.erb
<div id="page-content">
  <div class="container">
    <ol class="breadcrumb">
      <li><a href="/">Home</a></li>
      <li class="active">My Spaces</li>
    </ol>
    <!--end breadcrumb-->
    <section class="page-title">
      <h1>My Spaces</h1>
    </section>
    <!--end page-title-->
    <section>
      <div class="my-items table-responsive">
        <table class="table">
          <thead>
            <tr>
              <th>Spaces</th>
              <th>Featured</th>
              <th>Views</th>
              <th>Reviews</th>
              <th>Rating</th>
              <th>Last Edited</th>
            </tr>
          </thead>
          <tbody>
            <% @spaces.each do |space| %>
            <tr class="my-item">
              <td>
                <div class="image-wrapper">
                  <%if space.reviews.average(:rating) != nil && space.reviews.average(:rating) > 4 %>
                  <div class="circle" data-toggle="tooltip" data-placement="right" title="Top Listing"><i class="fa fa-thumbs-up"></i></div>
                  <%end%>
                  <div class="image" style="overflow: hidden;">
                    <%= image_tag space.image.url(:thumb) %>
                  </div>
                </div>
                <div class="info">
                  <h2><%= link_to space.name, space_path(space) %></h2>
                  <figure class="location"><%=space.city%>, <%=space.state%></figure>
                  <figure class="label label-info"><%=space.category.name%></figure>
                  <div class="additional-info">
                    <!-- <span><i class="fa fa-coffee"></i></span> -->
                    <span class="price-info"> <span class="price"></span><span class="appendix"></span></span>
                  </div>
                  <!--end additional-info-->
                </div>
                <!--end info-->
              </td>
              <% if space.reviews.average(:rating) != nil && space.reviews.average(:rating) > 3.8 && space.feature["Wifi"] != nil%>
              <td><div class="featured yes"><i class="fa fa-check"></i><aside></aside></div></td>
              <%else%>
              <td></td>
              <% end %>
              <td class="views"><%=space.favorite_spaces.count%></td>
              <td class="reviews"><%=space.reviews.count(:rating)%></td>
              <td class="rating">
                <% if space.reviews.blank? %>
                <p>No Reviews Yet!</p>
                <%else%>
                <div class="rating-passive" data-rating=<%=space.reviews.average(:rating)%>>
                  <span class="stars"></span><br>
                  <span class="reviews"><%="Average Rating: "%><%=space.reviews.average(:rating)%></span>
                </div>
                <%end%>
              </div>
            </td>
            <td class="last-edited"><%=space.updated_at.strftime("%b %d, %Y") + " at " + space.updated_at.strftime("%H:%M")%>
              <span class="last-edit">Last edited: <%=space.updated_at.strftime("%H:%M")%></span>
              <div class="edit-options">
                <a href="<%=edit_space_path(space)%>" class="link icon"><i class="fa fa-edit"></i>Edit</a>
                <a href="<%=space_path(space)%>" class="link icon"><i class="fa fa-comment"></i>Reviews</a>
              </div>
              <!--end edit-options-->
            </td>
          </tr>
          <%end%>
        </tbody>
      </table>
    </div>
    <!--end my-items-->
  </section>
  <section>
    <div class="center">

      <%= will_paginate @spaces %>

    </div>
  </section>
</div>
</div>
<!--end container-->

app/views/spaces/new.html.erb
<div id="page-content">
  <div class="container">
    <ol class="breadcrumb">
      <li><a href="/">Home</a></li>
      <li class="active">New Space</li>
    </ol>
    <!--end breadcrumb-->
    <section class="page-title center">
      <h1>Submit A Space</h1>

      <!-- <div class="form search-form horizontal no-background">
        <div class="container">
          <form>
            <div class="row text-center">
              <div class="col-md-3 col-md-offset-4">
                <div class="form-group">
                  <input type="text" placeholder="Type Food or City"></input>
                </div>
              </div>
              <div class="col-md-1 col-sm-4">
                <div class="form-group">
                  <div id="success"></div>
                  <button class="btn btn-primary pull-right">Search</button?
                </div>
              </div>
            </div>
          </form> -->

    </section>

<%= render 'form' %>

app/views/spaces/search.html.erb
<div class="page-wrapper">
  <div id="page-content">
    <div class="container">
      <ol class="breadcrumb">
        <li><a href="/">Home</a></li>
        <li><a href="/spaces">Spaces</a></li>
        <li class="active">Search</li>
      </ol>

      <section class="page-title">
        <h1>Search Results</h1>
      </section>
      <!--end section-title-->



      <section>
        <div class="search-results-controls clearfix">
          <div class="pull-left">
            <a href="" class="circle-icon active"><i class="fa fa-map"></i></a>
          </div>
          <!--end left-->
          <!-- <div class="pull-right">
            <div class="input-group inputs-underline min-width-150px">
              <select class="form-control selectpicker" name="sort">
                <option value="">Sort by</option>
                <option value="1">Price</option>
                <option value="2">Distance</option>
                <option value="3">Title</option>
              </select>
            </div>
          </div> -->
          <!--end right-->
        </div>
        <!--end search-results-controls-->
      </section>
      <section>

        <section>
        <div style='width: 100%;' id="show_map">
            <div class="map" id="map" style='width: 100%; height: 500px;'></div>
        </div>
      </section>


        <div class="row">
          <% @spaces.each do |space| %>
          <div class="col-md-4 col-sm-4">
            <div class="item" data-id="1">
              <span>
                <%=image_tag space.image.url(:large), class: "image" %>
                <div class="description">
                  <div class="label label-default"><%= "#{space.category.name}"%></div>
                  <h3 style="margin-top: 5px; margin-bottom: 5px;"><%= link_to "#{space.name}", space_path(space), style: "color: white; text-shadow: 0px 1px 1px rgba(0, 0, 0, 0.5);"  %></h3>
                  <h4 style="margin: 0;"><%=space.city%>, <%=space.state.upcase%></h4>
                </div>
                <!--end description-->



              </span>
              <!--end image-->
              <div class="additional-info">
                <div class="rating-passive" data-rating=<%=@spaces[-1].reviews.average(:rating)%>>
                  <div id="star"></div>
                  <% if space.reviews.average(:rating) == nil %>
                  <span class="reviews"><%= link_to "Be the first to Review!", space%></span>
                  <%else%>
                  <span class="reviews"><%=space.reviews.average(:rating)%></span>
                  <span class="star-rating" data-score=<%=@spaces[-1].reviews.average(:rating)%> ></span>
                  <%end%>
                  <% if current_user %>
                  <% if current_user.favorites.include? space %>
                  <div class="fav_button" style="float: right;">
                    <%= link_to "Unfavorite", favorite_space_path(space, type: "unfavorite"), class: "btn btn-primary btn-rounded btn-xs", method: :put %>
                  </div>
                  <%elsif current_user%>
                  <div class="fav_button" style="float: right;">
                    <%= link_to "Favorite", favorite_space_path(space, type: "favorite"), class: "btn btn-primary btn-rounded btn-xs", method: :put %>
                  </div>
                  <% end %>
                  <%else%>
                  <div class="fav_button" style="float: right;">
                    <%= link_to "Favorite", favorite_space_path(space, type: "favorite"), class: "btn btn-primary btn-rounded btn-xs", method: :put %>
                  </div>
                  <%end%>


                </div>

                <!--end controls-more-->
              </div>
              <!--end additional-info-->
              <!--end item-->

            </div>
          </div>
          <%end%>
          <!--<end col-md-3-->
        </div>
        <!--end row-->

      </section>
      <section>
        <div class="center">
          <nav aria-label="Page navigation">
            <ul class="pagination">
              <%= will_paginate @spaces %>
            </ul>
          </nav>
        </div>
      </section>


    </div>
    <!--end container-->
  </div>
</div>
<!--end page-content-->
<!--end page-wrapper-->
<a href="#page-header" class="to-top scroll" data-show-after-scroll="600"><i class="arrow_up"></i></a>

<script>
$('.star-rating').raty({
  path: '/assets',
  readOnly: true,
  score: function() {
    return $(this).attr('data-score');
  }
});
</script>


<script src="//maps.google.com/maps/api/js?key=AIzaSyDrG6_o9uHuGiIPiOipNnsZj_Jbizir93w"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->

<script type="text/javascript">
handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers(<%=raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});
</script>

<script type="text/javascript">
$(function() {
  $('.circle-icon').click(function(event){
    event.preventDefault();
    $('#map').toggle();
  });
});
</script>