config/routes.rb
Rails.application.routes.draw do
mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :posts do
    resources :comments
  end
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :subscribers
  resources :spaces do
    put :favorite, on: :member
    resources :reviews, except: [:index]
    resources :pictures
    resources :comments


    collection do
      get 'search'
    end
  end

  match "/404", :to => "errors#not_found", :via => :all

  root 'static#home'

  match "contact" => "contacts#create", :via => :post, :as => :create_contact
  get '/pending' => "static#pending"
  get '/users/:id' => 'static#user_profile'
  get '/spaces2' => "spaces#index2"
  get '/howitworks' => "static#howitworks"
  get '/contact' => "contacts#new"
  get '/blog' => "static#blog"
  get '/home1' => "static#home1"
  get '/map' => "spaces#map"
  get '/my_spaces' => "spaces#my_spaces"
  get '/my_reviews' => "reviews#my_reviews"
  get '/favorites' => "spaces#favorites"


end

app/models/contact.rb
class Contact < ActiveRecord::Base
  after_create :send_contact_mail, :send_contact_mail_notification
  def send_contact_mail
    Notifier.contact_email(self).deliver
  end

  def send_contact_mail_notification
    Notifier.contact_email_notification(self).deliver
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]
  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'We have received your message!' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.permit(:email, :name, :subject, :message)
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :subject %><br>
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_field :message %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Contacts</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Name</th>
      <th>Subject</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.email %></td>
        <td><%= contact.name %></td>
        <td><%= contact.subject %></td>
        <td><%= contact.message %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<div class="page-wrapper">
  <div id="page-content">
    <div class="container">
      <ol class="breadcrumb">
        <li><a href="/">Home</a></li>
        <li class="active">Contact</li>
      </ol>
      <section class="page-title">
        <h1 class="pull-left">Contact</h1>
      </section>
      <!--end section-title-->
    </div>
    <!--end container-->

    <section class="block">
      <div class="container">
        <div class="row">
          <div class="col-md-3 col-sm-3">
            <h3>Contact Information</h3>
            <div class="box">
              <address>
                <strong>Location</strong>
                <figure>San Francisco, CA</figure>
                <br>
                <strong>Phone Number</strong>
                <figure>+1 (954)292-5480</figure>
                <br>
                <strong>Email</strong>
                <figure><a href="#">info@remotespace.co</a></figure>
              </address>
            </div>
          </div>
          <!--end col-md-3-->
          <div class="col-md-9 col-sm-9">
            <h3>Form</h3>

            <%= form_for(contact_path, :html => { :multipart => true, :class => "form inputs-underline" }) do |f| %>
            <div class="row">
              <div class="col-md-4 col-sm-4">
                <div class="form-group">
                  <%= f.label :name %>
                  <%= f.text_field :name, class:"form-control", name: "name", id: "name" %>
                </div>
                <!--end form-group-->
              </div>
              <!--end col-md-4-->
              <div class="col-md-4 col-sm-4">
                <div class="form-group">
                  <%= f.label :email %>
                  <%= f.text_field :email, class:"form-control", name: "email", id: "email" %>
                </div>
                <!--end form-group-->
              </div>
              <!--end col-md-4-->
              <div class="col-md-4 col-sm-4">
                <div class="form-group">
                  <%= f.label :subject %>
                  <%= f.text_field :subject, class: "form-control" , name: "subject", id: "subject"%>
                </div>
                <!--end form-group-->
              </div>
              <!--end col-md-4-->
            </div>
            <!--end row-->
            <div class="col-sm-12 form-group">
              <%= f.label :message %><br><br>
              <%= f.text_area :message, class: "form-contol", id: "form-blog-reply-message", rows: "5", name: "message", style: "min-width: 100%;" %>
            </div>

            <!--end form-group-->
            <div class="form-group">
              <%= f.submit "Submit", class: "btn btn-primary"%>
            </div>
            <!--end form-group-->
            <%end%>

          </div>
          <!--end col-md-9-->
        </div>
        <!--end row-->
      </div>
      <!--end container-->
    </section>

  </div>
  <!--end page-content-->

</div>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @contact.subject %>
</p>

<p>
  <strong>Message:</strong>
  <%= @contact.message %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>