config/routes.rb
Rails.application.routes.draw do
mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :posts do
    resources :comments
  end
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :subscribers
  resources :spaces do
    put :favorite, on: :member
    resources :reviews, except: [:index]
    resources :pictures
    resources :comments


    collection do
      get 'search'
    end
  end

  match "/404", :to => "errors#not_found", :via => :all

  root 'static#home'

  match "contact" => "contacts#create", :via => :post, :as => :create_contact
  get '/pending' => "static#pending"
  get '/users/:id' => 'static#user_profile'
  get '/spaces2' => "spaces#index2"
  get '/howitworks' => "static#howitworks"
  get '/contact' => "contacts#new"
  get '/blog' => "static#blog"
  get '/home1' => "static#home1"
  get '/map' => "spaces#map"
  get '/my_spaces' => "spaces#my_spaces"
  get '/my_reviews' => "reviews#my_reviews"
  get '/favorites' => "spaces#favorites"


end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, only: [:create]
  before_action :set_space, :except => ["my_reviews"]
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
    @reviews = Review.where(review_id: @space)
  end

  # GET /reviews/new
  def new
    @review = Review.new(space: @space)
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = current_user.reviews.build(review_params)
    @review.space = @space
    respond_to do |format|
      if @review.save
        format.html { redirect_to @space, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @space }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def my_reviews
    @reviews = Review.where(user_id: current_user.id)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    def set_space
      @space = Space.find(params[:space_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:comment, :rating, :user_id)
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<section id="write-a-review">
  <h2>Write a Review</h2>
  <!-- <form class="clearfix form inputs-underline"> -->
    <div class="box">
      <div class="comment">
        <div class="row">
          <div class="col-md-8">
            <div class="comment-title">
              <h4>Review your experience</h4>
            </div>
            <!--end title-->
            <%= form_for([@space, @space.reviews.build]) do |f| %>

              <div class="form-group">
                <%= f.label :comment %><br>
                <%= f.text_area :comment, class: "form-control", id: "message" %>
              </div>
              <div class="form-group">
                <div id="star-rating"></div>
              </div>
              <div class="form-group text-center">
                <%= f.submit "Submit", class: "btn btn-primary btn-framed btn-rounded btn-light-frame" %>
              </div>
               <% end %>
          </div>

          <div class="col-md-4">

          </div>

        </div>
        <!--end row-->
      </div>
      <!--end comment-->
    </div>
    <!--end review-->
  <!-- </form> -->
  <!--end form-->
</section>
</div>

<script>
$('#star-rating').raty({
  path: '/assets/',
  scoreName: 'review[rating]'
});
</script>

app/views/reviews/_show.html.erb
<p id="notice"><%= notice %></p>
<section style="overflow: auto;">
  <h2>Reviews</h2>
  <div class="review">
    <div class="image">
      <%= image_tag @user.avatar.url(:review)%>
    </div>
    <div class="description">
      <figure>
        <div class="rating-passive">
          <span class="stars"><p>stars</p></span>
          <span class="reviews"><div class="clearfix star-rating" data-score=<%= @review.rating %> ></div> <div id="user_star"></div></span>
          <span class="reviews"><%=avg_rating%></span>
        </div>
        <span class="date"><%=Time.now%></span>
      </figure>
      <p><%=@review.comment%></p>
    </div>
  </div>
</section>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Comment</th>
      <th>Rating</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.comment %></td>
        <td><%= review.rating %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<section>
  <h2>Reviews</h2>
  <div class="review">
    <div class="image">
      <div class="bg-transfer"><img src="assets/img/person-02.jpg" alt=""></div>
    </div>
    <div class="description">
      <figure>
        <div class="rating-passive" data-rating="4">
          <span class="stars"></span>
          <span class="reviews">6</span>
          <span class="reviews"><%=review.rating%></span>
        </div>
        <span class="date"><%=Time.now%></span>
      </figure>
      <p><%=review.comment%></p>
    </div>
  </div>
</section>

app/views/reviews/my_reviews.html.erb
<div id="page-content">
  <div class="container">
    <ol class="breadcrumb">
      <li><a href="/">Home</a></li>
      <li class="active">My Reviews</li>
    </ol>
    <!--end breadcrumb-->
    <section class="page-title">
      <h1>My Reviews</h1>
    </section>
    <!--end page-title-->
    <section>
      <div class="my-items table-responsive">
        <table class="table">
          <thead>
            <tr>
              <th>Spaces</th>
              <th>Remote<br>Friendly</th>
              <th>Rating</th>
              <th>Posted On</th>
            </tr>
          </thead>
          <tbody>
            <% @reviews.each do |review| %>
            <tr class="my-item">
              <td>
                <div class="image-wrapper">
                  <div class="circle" data-toggle="tooltip" data-placement="right" title="Top Listing"><i class="fa fa-thumbs-up"></i></div>
                  <a href="edit-listing.html" class="image">
                    <div class="bg-transfer">
                      <img src="<%=review.space.image%>">
                    </div>
                  </a>
                </div>
                <div class="info">
                  <a href="detail.html"><h2><%=review.space.name%></h2></a>
                  <figure class="location"><%=review.comment%></figure>
                  <div class="additional-info">
                    <!-- <span><i class="fa fa-coffee"></i></span> -->
                    <span class="price-info"> <span class="price"></span><span class="appendix"></span></span>
                  </div>
                  <!--end additional-info-->
                </div>
                <!--end info-->
              </td>
              <td><div class="featured yes"><i class="fa fa-check"></i><aside></aside></div></td>


              <td class="rating">
                <div class="rating-passive" data-rating="4">
                  <div class="star-rating" data-score=<%=review.rating%>>
                </div>
              </td>
              <td class="last-edited"><%=review.created_at.strftime("%b %d, %Y") + " at " + review.created_at.strftime("%H:%M")%>

                <!--end edit-options-->
              </td>
            </tr>
            <%end%>
          </tbody>
        </table>
      </div>
      <!--end my-items-->
    </section>
    <section>
      <div class="center">
        <nav aria-label="Page navigation">
          <ul class="pagination">
            <li class="disabled previous">
              <a href="#" aria-label="Previous">
                <i class="arrow_right"></i>
              </a>
            </li>
            <li class="active"><a href="#">1</a></li>
            <li class="next">
              <a href="#" aria-label="Next">
                <i class="arrow_right"></i>
              </a>
            </li>
          </ul>
        </nav>
      </div>
    </section>
  </div>
  <!--end container-->
</div>

<script>
$('.star-rating').raty({
  path: '/assets',
  readOnly: true,
  score: function() {
    return $(this).attr('data-score');
  }
});
</script>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form' %>

<%= link_to 'Back', spaces_path %>